<<<<<<< HEAD
# Code for Azure Pipeline

=======
>>>>>>> 0769b6246f4ceeef803880faece5f03d7fa90c90
schedules:
  - cron: "0 * * * *" # cron syntax defining the schedule - every hour at 0'
    displayName: Hourly main schedule # friendly name given to a specific schedule
    branches:
      include: # which branches the schedule applies to
      - main 
#    exclude: # which branches to exclude from the schedule
#    - [string]
    always: false # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      cat /home/vsts/version/version.vote
      mkdir /home/vsts/version
      mkdir /home/vsts/git
      pwd
      ls -la
      TESTVAR=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
      echo "$TESTVAR"|sed 's/^.//;s/.$//' >/home/vsts/version/version.vote
      cat /home/vsts/version/version.vote

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Kubernetes Service Connection'
    command: 'apply'
    useConfigurationFile: true
    configuration: '/home/vsts/work/1/s/vote-renew.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
  displayName: 'Run Voting App s version renewal'