# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Kubernetes Service Connection'
    command: 'apply'
    useConfigurationFile: true
    configuration: '/home/vsts/Part_2/azure-vote.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
  displayName: 'Run Voting App deployment'

- task: CmdLine@2
  inputs:
    script: 
    cat /home/vsts/version/version.vote
    mkdir /home/vsts/version
    mkdir /home/vsts/git
    pwd
    ls -la
    TESTVAR=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
    echo "$TESTVAR"|sed 's/^.//;s/.$//' >/home/vsts/version/version.vote
    cat /home/vsts/version/version.vote
